class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'megamirror'
        self.UnzipMirrorCommand = 'megaunzipmirror'
        self.TarMirrorCommand = 'megatarmirror'
        self.CancelMirror = 'megacancel'
        self.CancelAllCommand = 'megacancelall'
        self.ListCommand = 'listmega'
        self.StatusCommand = 'megastatus'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restartmega'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'megaspeedtest'
        self.CloneCommand = 'megaclone'
        self.CountCommand = 'count'
        self.WatchCommand = 'megawatch'
        self.TarWatchCommand = 'megatarwatch'
        self.DeleteCommand = 'del'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
